/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Clock_1K.h"
#include "ADC.h"
#include "ADC_FILTER.h"
#include "POT_PIN.h"
#include "POT_PIN_aliases.h"
#include "LED_STRIP.h"
#include "LED_STRIP_aliases.h"
#include "LED_BLUE.h"
#include "LED_BLUE_aliases.h"
#include "LED_GREEN.h"
#include "LED_GREEN_aliases.h"
#include "LED_RED.h"
#include "LED_RED_aliases.h"
#include "MIC_ANALOG.h"
#include "MIC_ANALOG_aliases.h"
#include "PWM_LED_Strip.h"
#include "Clock_12M.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "Pin_PIR.h"
#include "Pin_PIR_aliases.h"
#include "Pin_AmpOut.h"
#include "Pin_AmpOut_aliases.h"
#include "PIRAmplifierStage1.h"
#include "RefBuffer.h"
#include "PVref.h"
#include "Pin_Vref.h"
#include "Pin_Vref_aliases.h"
#include "Pin_PIRRef.h"
#include "Pin_PIRRef_aliases.h"
#include "Pin_PGAIn.h"
#include "Pin_PGAIn_aliases.h"
#include "PIRAmplifierStage2.h"
#include "PIRAmplifierStage2_PVT.h"
#include "Clock_200.h"
#include "Switch_Off_Timer.h"
#include "Switch_Off_Timer_Int.h"
#include "Millis_Update_Timer.h"
#include "Millis_Update_Timer_Int.h"
#include "CSD.h"
#include "CSD_Control.h"
#include "CSD_Filter.h"
#include "CSD_Processing.h"
#include "CSD_Sensing.h"
#include "CSD_Structure.h"
#include "CSD_Tuner.h"
#include "CSD_Configuration.h"
#include "CSD_SensingCSD_LL.h"
#include "CSD_RegisterMap.h"
#include "ADC_intSarClock.h"
#include "ADC_IRQ.h"
#include "ADC_intUabClock.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "CSD_ISR.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cm0plus_psoc4.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

